# Generated by Django 2.0.7 on 2019-04-12 15:02

import DjangoUeditor.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='姓名')),
                ('address', models.CharField(max_length=100, verbose_name='地址')),
                ('phone', models.CharField(max_length=20, verbose_name='电话')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
            ],
            options={
                'verbose_name': '博主信息',
                'verbose_name_plural': '博主信息',
            },
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='标题')),
                ('img', models.ImageField(upload_to='articles', verbose_name='封面图')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('click_nums', models.IntegerField(default=0, verbose_name='阅读数')),
                ('comment_nums', models.IntegerField(default=0, verbose_name='评论数')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='点赞数')),
                ('content', DjangoUeditor.models.UEditorField(default='', verbose_name='博文内容')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.AdminUser', verbose_name='作者')),
            ],
            options={
                'verbose_name': '博文管理',
                'verbose_name_plural': '博文管理',
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名称')),
                ('img', models.ImageField(upload_to='categories', verbose_name='类别图片')),
                ('info', models.TextField(verbose_name='简介')),
            ],
            options={
                'verbose_name': '博文分类',
                'verbose_name_plural': '博文分类',
            },
        ),
        migrations.CreateModel(
            name='CommenttUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=10, verbose_name='用户昵称')),
                ('usericon', models.ImageField(upload_to='users', verbose_name='用户头像')),
                ('area', models.CharField(max_length=100, verbose_name='地址')),
                ('gender', models.BooleanField(default=1, verbose_name='性别')),
            ],
            options={
                'verbose_name': '评论用户',
                'verbose_name_plural': '评论用户',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20, verbose_name='名称')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '标签管理',
                'verbose_name_plural': '标签管理',
            },
        ),
        migrations.AddField(
            model_name='articles',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Categories', verbose_name='所属类别'),
        ),
        migrations.AddField(
            model_name='articles',
            name='tags',
            field=models.ManyToManyField(to='articles.Tags'),
        ),
    ]
