# Generated by Django 2.0.7 on 2019-04-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='is_index',
            field=models.BooleanField(default=1, verbose_name='是否首页轮播'),
        ),
    ]
