# Generated by Django 2.0.7 on 2019-04-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_categories_is_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='se_name',
            field=models.CharField(default=1, max_length=50, verbose_name='副标题'),
            preserve_default=False,
        ),
    ]
