# Generated by Django 2.0.7 on 2019-04-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_categories_se_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='articles', verbose_name='封面图'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='categories', verbose_name='类别图片'),
        ),
    ]
