# Generated by Django 2.0.7 on 2019-04-12 16:17

import DjangoUeditor.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20190412_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jottings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='标题')),
                ('img', models.ImageField(blank=True, null=True, upload_to='articles', verbose_name='封面图')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('click_nums', models.IntegerField(default=0, verbose_name='阅读数')),
                ('comment_nums', models.IntegerField(default=0, verbose_name='评论数')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='点赞数')),
                ('content', DjangoUeditor.models.UEditorField(default='', verbose_name='博文内容')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.AdminUser', verbose_name='作者')),
                ('tags', models.ManyToManyField(to='articles.Tags')),
            ],
            options={
                'verbose_name': '心情随笔',
                'verbose_name_plural': '心情随笔',
            },
        ),
    ]
