# Generated by Django 2.0.7 on 2019-04-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_jottings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': '博文', 'verbose_name_plural': '博文'},
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name': '标签', 'verbose_name_plural': '标签'},
        ),
        migrations.RemoveField(
            model_name='categories',
            name='info',
        ),
        migrations.AddField(
            model_name='articles',
            name='info',
            field=models.CharField(default='', max_length=200, verbose_name='摘要'),
        ),
    ]
