# Generated by Django 2.0.7 on 2019-04-12 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20190412_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='img',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='is_index',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='se_name',
        ),
    ]
