# Generated by Django 2.0.7 on 2019-04-12 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20190412_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='is_index',
            field=models.BooleanField(default=0, verbose_name='是否首页轮播'),
        ),
    ]
