# Generated by Django 2.0.7 on 2019-04-13 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_articles_is_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItsMe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=2, verbose_name='标签')),
                ('title', models.CharField(max_length=10, verbose_name='标题')),
                ('se_title', models.CharField(max_length=10, verbose_name='副标题')),
                ('info', models.CharField(max_length=40, verbose_name='副标题')),
            ],
            options={
                'verbose_name': "It's Me",
                'verbose_name_plural': "It's Me",
            },
        ),
    ]
