# Generated by Django 2.0.7 on 2019-04-15 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_itsme'),
    ]

    operations = [
        migrations.AddField(
            model_name='jottings',
            name='info',
            field=models.CharField(default='随笔，顾名思义。就是在想记叙某件事的时候，稍稍写上几笔，叫做随笔，而心情随笔就是，表诉心情的喜，怒，哀，乐时记叙的文字。', max_length=200, verbose_name='摘要'),
        ),
    ]
