# Generated by Django 2.0.7 on 2019-04-15 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_jottings_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('subject', models.CharField(max_length=100, verbose_name='主题')),
                ('message', models.TextField(verbose_name='内容')),
            ],
            options={
                'verbose_name': '留言处理',
                'verbose_name_plural': '留言处理',
            },
        ),
    ]
