# Generated by Django 2.0.7 on 2019-04-20 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_getmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='commenttuser',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.Articles', verbose_name='文章评论'),
        ),
        migrations.AddField(
            model_name='commenttuser',
            name='comment',
            field=models.TextField(null=True, verbose_name='评论内容'),
        ),
    ]
